#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 4, rgba16f) uniform image2D postProcessImages[];

layout(push_constant) uniform PushConstants {
    float exposure;
    float saturation;
    float contrast;

    float padding;
    
    layout(offset = 16) vec4 colorTint;
} pc;

void main() {
    float tempExposure = 1.0; 

    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    
    ivec2 size = imageSize(postProcessImages[0]); 

    if (uv.x >= size.x || uv.y >= size.y) return;

    vec3 color = imageLoad(postProcessImages[0], uv).rgb;

    if (isnan(color.r) || isnan(color.g) || isnan(color.b) || 
        isinf(color.r) || isinf(color.g) || isinf(color.b)) 
    {
        color = vec3(0.0);
    }

    color *= tempExposure;
    color *= pc.colorTint.rgb;

    color = (color - vec3(0.18)) * pc.contrast + vec3(0.18);
    color = max(vec3(0.0), color);

    float luma = dot(color, vec3(0.2126, 0.7152, 0.0722));
    color = mix(vec3(luma), color, pc.saturation);
    color = max(vec3(0.0), color);

    imageStore(postProcessImages[0], uv, vec4(color, 1.0));
}
