#version 460
#extension GL_EXT_nonuniform_qualifier : require
layout(local_size_x = 16, local_size_y = 16) in;

// Тут хранятся картинки рендера
layout(set = 1, binding = 4, rgba16f) uniform image2D globalScreenImages[];

const uint CURRENT_COLOR_IDX    = 0;
const uint DEPTH_IDX            = 1;
const uint VELOCITY_IDX         = 2;
const uint NORMAL_IDX           = 3;
const uint HISTORY_0_IDX        = 4;
const uint HISTORY_1_IDX        = 5;

layout(push_constant) uniform Constants {
    uint frameIndex;
    float screenWidth;
    float screenHeight;
} pc;

void main() {
    
}