#version 460

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba16f) uniform image2D image;

layout(push_constant) uniform constants
{
	vec4 data1; // x = iTime
	vec4 data2;
	vec4 data3;
	vec4 data4;
} PushConstants;

#define PI 3.14159265

vec3 palette(in float t) {
    vec3 a = vec3(0.5, 0.5, 0.5);
    vec3 b = vec3(0.5, 0.5, 0.5);
    vec3 c = vec3(1.0, 1.0, 1.0);
    vec3 d = vec3(0.1, 0.4, 0.5);
    return a + b * cos(2.0 * PI * (c * t + d));
}

// Функция волны
vec4 wave(vec2 uv, vec4 color, float amp, float freq, float phase, float thick, vec3 hue) {
    float x = uv.x - phase;
    float y = uv.y + amp * sin(freq * x);
    float bright = smoothstep(0.0, 1.0, 1.0 - abs(y) / thick);
    return vec4(vec3(bright) * hue, 1.0);
}

void main() {
    // Переводим в значения для шейдера с сайта ShaderToy
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);
    vec2 iResolution = vec2(size);
    float iTime = PushConstants.data1.x;    

    vec2 coord = vec2(texelCoord.x, iResolution.y - float(texelCoord.y));

    vec2 uv = (2.0 * coord - iResolution.xy) / iResolution.y;

    vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

    for (float layer = 0.0; layer < 1.0; layer += 0.1) {
        float amp = 0.25 + 0.25 * sin(iTime + layer) * (1.0 - layer);
        float freq = 2.0;
        float phase = iTime * (1.0 - layer);
        float thick = 0.01 + 0.001 * pow(abs(uv.x), 8.0);
        vec3 hue = palette(0.5 * uv.x + 1.0 * layer - 0.5 * iTime);
        color += wave(uv, color, amp, freq, phase, thick, hue);
    }
    
    // Записываем в текстуру изображения нашу волну
    imageStore(image, texelCoord, color);
}