#version 460
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 1, binding = 2) uniform sampler2D skyPanoramaTex;
layout(set = 1, binding = 3, rgba16f) uniform writeonly imageCube iblStorageMaps[];

const vec2 invAtan = vec2(0.15915494, 0.31830988);
const float PI = 3.14159265359;

vec2 SampleSphericalMap(vec3 v) {
    vec2 uv = vec2(atan(v.y, v.x), asin(v.z));
    uv *= vec2(0.15915494, 0.31830988);
    uv += 0.5;
    uv.y = 1.0 - uv.y;
    return uv;
}

vec3 GetCubeDirection(vec2 uv, uint face) {
    vec3 dir = vec3(0.0);
    
    if(face == 0) dir = vec3( 1.0, -uv.x, -uv.y); // r.x > 0
    if(face == 1) dir = vec3(-1.0,  uv.x, -uv.y); // r.x < 0
    if(face == 2) dir = vec3( uv.x,  1.0, -uv.y); // r.y > 0
    if(face == 3) dir = vec3(-uv.x, -1.0, -uv.y); // r.y < 0
    if(face == 4) dir = vec3( uv.x, -uv.y,  1.0); // r.z > 0
    if(face == 5) dir = vec3( uv.x,  uv.y, -1.0); // r.z < 0
    
    return normalize(dir);
}

void main() {
    ivec3 cubeCoord = ivec3(gl_GlobalInvocationID);
    ivec2 size = imageSize(iblStorageMaps[1]); // Достаем размер Specular (512x512)

    if (cubeCoord.x >= size.x || cubeCoord.y >= size.y) return;

    // Переводим пиксели в диапазон [-1, 1]
    vec2 uv = (vec2(cubeCoord.xy) + 0.5) / vec2(size) * 2.0 - 1.0;
    
    vec3 dir = GetCubeDirection(uv, cubeCoord.z);
    vec2 texUV = SampleSphericalMap(dir);
    
    vec4 color = texture(skyPanoramaTex, texUV);
    
    // Пишем в Specular кубмапу (ID = 1)
    imageStore(iblStorageMaps[1], cubeCoord, color);
}
